export const publicComponentCatalog = [
  { component: 'AreaChart', owner: 'components/charts', status: '稳定', tone: 'success' },
  { component: 'BarChart', owner: 'components/charts', status: '稳定', tone: 'success' },
  { component: 'Button', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Checkbox', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'DataTable', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'DangerZone', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'DesignTokenCatalog', owner: 'components/design-system', status: '稳定', tone: 'success' },
  { component: 'DestructiveActionDialog', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'DonutChart', owner: 'components/charts', status: '稳定', tone: 'success' },
  { component: 'DropdownMenu', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'FormField', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'ListToolbar', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Modal', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'PageHeader', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'PageState', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Panel', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'ProgressBar', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'RadioGroup', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Select', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Skeleton', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'StatusBadge', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Switch', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'TablePagination', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Tabs', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'TextInput', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Textarea', owner: 'components/ui', status: '稳定', tone: 'success' },
  { component: 'Tooltip', owner: 'components/ui', status: '稳定', tone: 'success' },
] as const

export type PublicComponentCatalogRow = (typeof publicComponentCatalog)[number]
